version: '3.1'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bootcamp
    ports:
      - "3306:3306"
    volumes:
    - mysql:/var/lib/mysql
    - ./book_data.sql:/docker-entrypoint-initdb.d/book_data.sql
volumes:
  mysql:

# start with "docker-compose up -d" "docker-compose exec db mysql -uroot -proot"